### ISSUE TITLE
[META][AutoDiff] Tech debt from tests

### ISSUE THREAD

**Issue by kovdan01** [swiftlang/swift#77773]
### Description

I've assigned preliminary priorities for the issues, but this should be revisited.

## High priority:

- [ ] #54214 
  **Note:** FIXME(TF-977): Fix incorrect derivative for array literal with `tuple_element_addr` elements.
  **Test:** test/AutoDiff/validation-test/array.swift

- [ ] **Note:** FIXME(TF-584): Investigate incorrect (too big) gradient values for repeat-while loops.
   **Test:** test/AutoDiff/validation-test/control_flow.swift

## Medium priority:

- [ ] **Note:** FIXME: missing reverse-mode differentiability witness for foo(_:)
   **Test:** test/AutoDiff/SILGen/has_symbol.swift

- [ ] **Note:** FIXME(TF-1176): Some values are incorrectly not marked as active: `%16`, etc.
   **Test:** test/AutoDiff/SILOptimizer/activity_analysis.swift

   This is probably class-related, but need to ensure that for non-class cases the issue is not present.

- [ ] **Note:** TODO(TF-1030): This will eventually not be an error.
   **Test:** test/AutoDiff/SILOptimizer/differentiation_diagnostics.swift (see `hasImplicitlyDifferentiatedClosureDefaultArgument`).

   The same error was fixed for curry thunks in #77615

- [ ] #54231
   **Note:** TODO(TF-982): Lift this restriction and add proper support.
   **Test:** test/AutoDiff/Sema/derivative_attr_type_checking.swift

- [ ] **Note:** FIXME(TF-284): Fix unexpected diagnostic.
   **Test:** AutoDiff/Sema/differentiable_attr_type_checking.swift

- [ ] #54445 
   **Note:** FIXME(TF-1103): Derivative registration does not yet support `@_alwaysEmitIntoClient` original functions.
   **Test:** AutoDiff/stdlib/simd.swift

- [ ] #55690 
   **Note:** FIXME: Disabled due to test failure with `-O`
   **Test:** test/AutoDiff/validation-test/differentiable_protocol_requirements.swift

- [ ] #54628
   **Note:** TODO(TF-433): operator `??` lowers to an active `try_apply`.
   **Test:** test/AutoDiff/validation-test/optional.swift

- [ ] #55084 
   **Note:** TODO: Support `modify` accessors
   **Test:** test/AutoDiff/validation-test/property_wrappers.swift

## Low priority:

- [ ] **Note:** TODO: Re-enable the boolean-literal-folding pass and fix the test accordingly
   **Test:** test/AutoDiff/SILOptimizer/activity_analysis.swift

- [ ] #77762

- [ ] **Note:** TODO(TF-956): Improve location of active enum non-differentiability errors
  **Test:** test/AutoDiff/SILOptimizer/differentiation_control_flow_diagnostics.swift

- [ ] **Note:** TODO(TF-957): Improve non-differentiability errors for for-in loops
  **Test:** test/AutoDiff/SILOptimizer/differentiation_control_flow_diagnostics.swift

- [ ] **Note:** TODO(TF-788): Re-enable non-varied result warning.
  **Test:** test/AutoDiff/SILOptimizer/differentiation_diagnostics.swift

- [ ] **Note:** TODO(TF-482): Remove diagnostics when `@differentiable` attributes are also uniqued based on generic requirements.
  **Test:** test/AutoDiff/Sema/differentiable_attr_type_checking.swift

- [ ] **Note:** TODO(TF-650): It would be nice to diagnose protocol default implementation with missing `@differentiable` attribute.
  **Test:** test/AutoDiff/Sema/differentiable_attr_type_checking.swift

- [ ] **Note:** TODO(TF-632): Fix "'TangentVector' is not a member type of 'Self'" diagnostic. The underlying error should appear instead: "covariant 'Self' can only appear at the top level of method result type".
  **Test:** test/AutoDiff/Sema/differentiable_attr_type_checking.swift

- [ ] **Note:** FIXME: Enable test for all platforms after debugging (https://github.com/apple/swift/issues/55186).
  **Test:** test/AutoDiff/validation-test/control_flow.swift

- [ ] **Note:** TODO(TF-851): Uncomment the tests below after `@differentiable` function SILGen thunking is fixed.
  **Test:** test/AutoDiff/SILOptimizer/generics.swift
  This actually looks fixed, and tests might be uncommented, but need to ensure that.

- [ ] **Note:** TODO(TF-1065): Consider disallowing qualified operators / operator names
   **Tests:**
   1. test/AutoDiff/Parse/transpose_attr_parse.swift
   2. test/AutoDiff/Sema/transpose_attr_type_checking.swift

## Existing issues to consider closing as not planned:

1. **Class-related**:

   1. #65012 and its sub-issues.
   2. #52130 and its sub-issues.

2. **Forward-mode-related**:

   1. #55906
   2. #55650

## Entire tests to consider deleting after dropping support for corresponding features:

1. **Class-related**:

   1. test/AutoDiff/SILGen/vtable.swift
   2. test/AutoDiff/Sema/DerivedConformances/class_differentiable.swift
   3. test/AutoDiff/validation-test/class_differentiation.swift

2. **Forward-mode-related**:

   1. test/AutoDiff/SILOptimizer/forward_mode_diagnostics.swift
   2. test/AutoDiff/validation-test/forward_mode_simd.swift
   3. test/AutoDiff/validation-test/forward_mode_simple.swift

### Class-related:

   1. **Note:** FIXME(rdar://74380324)
      **Test:** test/AutoDiff/TBD/derivative_symbols.swift
      FIXMEs are related to initializer and other special functions differentiation support
   2. **Note:** FIXME(TF-1080): Fix incorrect class property `modify` accessor derivative values.
      **Test:** test/AutoDiff/validation-test/inout_parameters.swift
   3. **Note:** TODO(TF-649): Enable `@derivative` to override derivatives for original declaration defined in superclass.
      **Test:** test/AutoDiff/Sema/derivative_attr_type_checking.swift
   4. **Note:** FIXME: Enable derivative registration for class property/subscript setters (https://github.com/apple/swift/issues/55542).
      **Test:** test/AutoDiff/Sema/derivative_attr_type_checking.swift
      This looks working for structs.
   5. **Note:** FIXME(rdar://74380324)\
      **Test:** test/AutoDiff/TBD/derivative_symbols.swift
      The FIXME is related to the following crash:
      ```
      1.      Swift version 6.1-dev (LLVM 0f86f354a7bc883, Swift e6b4e0f9f171a51)
      2.      Compiling with effective version 4.1.50
      3.      While evaluating request ASTLoweringRequest(Lowering AST to SIL for module test)
      4.      While verifying SIL function "@$s4test5ClassCyACSfcfCTJVfSUpSr".test/AutoDiff/TBD/derivative_symbols.swift
      ```
   6. **Note:** // FIXME(TF-1175): Class operands should always be marked active.
      **Test:** test/AutoDiff/validation-test/property_wrappers.swift

### Forward-mode-related:

   1. **Note:** TODO(TF-1254): Support forward-mode differentiation and test generated differentials.
      **Test:** test/AutoDiff/SILOptimizer/semantic_member_accessors_sil.swift
   2. **Note:** TODO(TF-1173): Move floating-point mutating operation tests to `test/AutoDiff/stdlib/floating_point.swift.gyb` when forward-mode differentiation supports `inout` parameter differentiation.
      **Test:** test/AutoDiff/validation-test/inout_parameters.swift
   3. **Note:** TODO(TF-1254): Support and test forward-mode differentiation.
   **Test:**test/AutoDiff/validation-test/property_wrappers.swift
   4. **Note:** FIXME(TF-1033): Fix forward-mode ownership error for tuple with non-active
   **Test:** test/AutoDiff/validation-test/simple_math.swift

### Linear functions related:

   1. **Note:** TODO(TF-900, TF-902): Uncomment the following line to test loading a linear function from memory and direct calls to a linear function.
      **Test:** test/AutoDiff/SILGen/differentiable_function.swift
   2. **Note:** TODO: Add tests for `@differentiable(_linear)` functions.
     **Test:** test/AutoDiff/IRGen/loadable_by_address.swift

**Comment by kovdan01** [comment]
Tagging @asl

**Comment by JaapWijnen** [comment]
Oh also, the TF related links don't seem to work and redirect to the following page: https://github.com/apple/swift-issues/issues 

Is this a recent change that these issues are no longer hosted there? Not sure I haven't looked at the page for a while.

**Comment by kovdan01** [comment]
> Oh also, the TF related links don't seem to work and redirect to the following page: https://github.com/apple/swift-issues/
>
> Is this a recent change that these issues are no longer hosted there? Not sure I haven't looked at the page for a while.

It looks like they are not hosted there for at least several months. As far as I understood, they are just gone and were not transferred properly (some of them were, but not all of them), unfortunately.

It looks like that swift repository still has some rules so TF-XXX text in issues is automatically converted to corresponding dangling link - it might be a bit confusing.

@asl Please correct me if I'm mistaken

**Comment by asl** [comment]
TF issues from TensorFlow Jira were never converted to github issues. So, they are gone forever.

**Comment by kovdan01** [comment]
@JaapWijnen Thanks for assigning priorities! One minor comment regarding the following: it looks like that the observable error is the same but root cause is different (not related to curry thunks). So it looks like it would need a separate patch

> * _Note: TODO([TF-1030](https://bugs.swift.org/browse/TF-1030)): This will eventually not be an error._ (which you've already provided a fix for)
